

gmail:
  domain:
    gmail-auth: https://accounts.google.com
    gmail-api: https://gmail.googleapis.com
  client-id: 806487491033-43nlnqg49q9rsetnv69jhi8o2qnjbcl5.apps.googleusercontent.com
  user-id: newslettercollector77@gmail.com
  access-token: "ya29.a0AWY7CkmKrkxtPsmDIjK6fbMlOniSmXq9f_zrrmIMmWR9Ph06c6bGlTPrGKQH0lwbygIbra1nxKVlBj_C-MRap7fCH56oYMXPT4Js7b-8qI1SkDDcbWt8QQPVOwBtlVPgqU41D7I_iny4U78zAev6veivVjdyaCgYKAVgSARISFQG1tDrpjGvAG0JaFrEqY71WI-mOYw0163"
